DROP_FEATURES = ["Check","NEWSOSites","SOVisitFreq","SOAccount","SOPartFreq","SOHow","SOComm",
                 "Knowledge_1","Knowledge_2","Knowledge_3","Knowledge_4","Knowledge_5","Knowledge_6",
                 "Knowledge_7","Knowledge_8","Knowledge_9","Frequency_1","Frequency_2","Frequency_3",
                 "SurveyLength","SurveyEase",
                 "JobSatPoints_1","JobSatPoints_4","JobSatPoints_5","JobSatPoints_6","JobSatPoints_7",
                 "JobSatPoints_8","JobSatPoints_9","JobSatPoints_10","JobSatPoints_11",
                 "LearnCodeOnline","TechDoc",
                 "PurchaseInfluence","BuyNewTool","BuildvsBuy","TechEndorse", "Currency",
                 "LanguageAdmired", "PlatformAdmired" ,"DatabaseAdmired", "WebframeAdmired", "EmbeddedAdmired",
                 "MiscTechHaveWorkedWith","MiscTechWantToWorkWith","MiscTechAdmired", 
                 "ToolsTechHaveWorkedWith","ToolsTechWantToWorkWith","ToolsTechAdmired","NEWCollabToolsHaveWorkedWith",
                 "NEWCollabToolsWantToWorkWith","NEWCollabToolsAdmired",
                 "LanguageWantToWorkWith","DatabaseWantToWorkWith","PlatformWantToWorkWith",
                 "WebframeWantToWorkWith", "EmbeddedWantToWorkWith",
                 "OfficeStackAsyncHaveWorkedWith","OfficeStackAsyncWantToWorkWith","OfficeStackAsyncAdmired",
                 "OfficeStackSyncHaveWorkedWith","OfficeStackSyncWantToWorkWith","OfficeStackSyncAdmired",
                 "AISearchDevWantToWorkWith","AISearchDevAdmired", "AISent","AIComplex",
                 "AIToolInterested in Using","AIToolNot interested in Using",
                 "AINextMuch more integrated","AINextNo change",
                 "AINextMore integrated","AINextLess integrated","AINextMuch less integrated",
                 "ProfessionalQuestion","ConvertedCompYearly","ProfessionalTech","ProfessionalCloud",
                 "TimeSearching","TimeAnswering","TBranch"]