DROP_FEATURES = ["Check","NEWSOSites","SOVisitFreq","SOAccount","SOPartFreq","SOHow","SOComm",
                 "Knowledge_1","Knowledge_2","Knowledge_3","Knowledge_4","Knowledge_5","Knowledge_6",
                 "Knowledge_7","Knowledge_8","Knowledge_9","Frequency_1","Frequency_2","Frequency_3",
                 "SurveyLength","SurveyEase",
                 "JobSatPoints_1","JobSatPoints_4","JobSatPoints_5","JobSatPoints_6","JobSatPoints_7",
                 "JobSatPoints_8","JobSatPoints_9","JobSatPoints_10","JobSatPoints_11",
                 "LearnCodeOnline","TechDoc",
                 "PurchaseInfluence","BuyNewTool","BuildvsBuy","TechEndorse", "Currency",
                 "LanguageAdmired", "PlatformAdmired" ,"DatabaseAdmired", "WebframeAdmired", "EmbeddedAdmired",
                 "MiscTechHaveWorkedWith","MiscTechWantToWorkWith","MiscTechAdmired", 
                 "ToolsTechHaveWorkedWith","ToolsTechWantToWorkWith","ToolsTechAdmired","NEWCollabToolsHaveWorkedWith",
                 "NEWCollabToolsWantToWorkWith","NEWCollabToolsAdmired",
                 "LanguageWantToWorkWith","DatabaseWantToWorkWith","PlatformWantToWorkWith",
                 "WebframeWantToWorkWith", "EmbeddedWantToWorkWith",
                 "OfficeStackAsyncHaveWorkedWith","OfficeStackAsyncWantToWorkWith","OfficeStackAsyncAdmired",
                 "OfficeStackSyncHaveWorkedWith","OfficeStackSyncWantToWorkWith","OfficeStackSyncAdmired",
                 "AISearchDevWantToWorkWith","AISearchDevAdmired", "AISent","AIComplex",
                 "AIToolInterested in Using","AIToolNot interested in Using",
                 "AINextMuch more integrated","AINextNo change",
                 "AINextMore integrated","AINextLess integrated","AINextMuch less integrated",
                 "ProfessionalQuestion","ConvertedCompYearly","ProfessionalTech","ProfessionalCloud",
                 "TimeSearching","TimeAnswering","TBranch", "LearnCode",]
mapping_industry = {
    "Software Development": 1,
    "Computer Systems Design and Services": 2,
    "Internet, Telecomm or Information Services": 3,
    "Fintech": 4,
    "Energy": 5,
    "Government": 6,
    "Banking/Financial Services": 7,
    "Manufacturing": 8,
    "Transportation, or Supply Chain": 9,
    "Healthcare": 10,
    "Retail and Consumer Services": 11,
    "Higher Education": 12,
    "Media & Advertising Services": 13,
    "Insurance": 14,
    "Other": 0
}
mapping_frustration = {
    "Complexity of tech stack for build": 1,
    "Complexity of tech stack for deployment": 2,
    "Amount of technical debt": 3,
    "Number of software tools in use": 4,
    "Patching/updating core components": 5,
    "Maintaining security of code being produced": 6,
    "Maintaining security of systems/platforms used in work": 7,
    "Reliability of tools/systems used in work": 8,
    "Tracking my work": 9,
    "Showing my contributions": 10,
    "None of these": 0
}
mapping_icorpm = {
    "Individual contributor": 1,
    "People manager": 2
}
mapping_aichallenges = {
    "Don’t trust the output or answers": 1,
    "AI tools lack context of codebase, internal architecture, and/or company knowledge": 2,
    "They create more work (more code/PRs to review, etc.)": 3,
    "We don’t have the right policies in place to reduce security risks": 4,
    "Not everyone uses them": 5,
    "Lack of executive buy-in": 6,
    "Lack of proper training and education on new tools": 7,
    "None of the above": 8,
    "Other (please specify)": 0
}
mapping_aiethics = {
    "Biased results that do not represent diverse viewpoints": 1,
    "Circulating misinformation or disinformation": 2,
    "Imitating a person's likeness": 3,
    "Replacing jobs without options for new employment opportunities": 4,
    "Energy demand": 5,
    "Missing or incorrect attribution for sources of data": 6,
    "Other (please specify)": 0
}
mapping_aithreat = {
    "Yes": 1,
    "No": 2,
    "I'm not sure": 0
}
mapping_aitool = {
    "Learning about a codebase": 1,
    "Project planning": 2,
    "Writing code": 3,
    "Documenting code": 4,
    "Debugging and getting help": 5,
    "Testing code": 6,
    "Committing and reviewing code": 7,
    "Deployment and monitoring": 8,
    "Predictive analytics": 9,
    "Search for answers": 10,
    "Generating content or synthetic data": 11,
    "Other (please specify)": 0
}
mapping_aiacc = {
    "Highly trust": 1,
    "Somewhat trust": 2,
    "Neither trust nor distrust": 3,
    "Somewhat distrust": 4,
    "Highly distrust": 5
}
mapping_aiben = {
    "Increase productivity": 1,
    "Greater efficiency": 2,
    "Make workload more manageable": 3,
    "Improve collaboration": 4,
    "Speed up learning": 5,
    "Improve accuracy in coding": 6,
    "None of the above": 7,
    "Other (please specify)": 0
}
mapping_aiselect = {
    "Yes": 1,
    "No, but I plan to soon": 2,
    "No, and I don't plan to": 3
}
mapping_aisearchdev = {
    "Andi": 1,
    "AskCodi": 2,
    "Amazon Q": 3,
    "Bing AI": 4,
    "ChatGPT": 5,
    "Claude": 6,
    "Codeium": 7,
    "Cody": 8,
    "GitHub Copilot": 9,
    "Google Gemini": 10,
    "Lightning AI": 11,
    "Meta AI": 12,
    "Metaphor": 13,
    "Neeva AI": 14,
    "OpenAI Codex": 15,
    "Perplexity AI": 16,
    "Phind": 17,
    "Quora Poe": 18,
    "Replit Ghostwriter": 19,
    "WolframAlpha": 20,
    "Snyk Code": 21,
    "Tabnine": 22,
    "Visual Studio Intellicode": 23,
    "Whispr AI": 24,
    "You.com": 25,
    "Other (please specify)": 0
}
mapping_opsys = {
    "AIX": 1,
    "Android": 2,
    "Arch": 3,
    "BSD": 4,
    "ChromeOS": 5,
    "Cygwin": 6,
    "Debian": 7,
    "Fedora": 8,
    "Haiku": 9,
    "iOS": 10,
    "iPadOS": 11,
    "MacOS": 12,
    "Other Linux-based": 13,
    "Red Hat": 14,
    "Solaris": 15,
    "Ubuntu": 16,
    "Windows": 17,
    "Windows Subsystem for Linux (WSL)": 18,
    "Other (please specify)": 0
}
mapping_embedded = {
    "Arduino": 1,
    "Boost.Test": 2,
    "build2": 3,
    "Catch2": 4,
    "CMake": 5,
    "Cargo": 6,
    "cppunit": 7,
    "CUTE": 8,
    "doctest": 9,
    "GNU GCC": 10,
    "LLVM's Clang": 11,
    "Meson": 12,
    "Micronaut": 13,
    "MSVC": 14,
    "Ninja": 15,
    "PlatformIO": 16,
    "QMake": 17,
    "Raspberry Pi": 18,
    "SCons": 19,
    "ZMK": 20,
    "Other (please specify)": 0
}
mapping_webframe = {
    "Angular": 1,
    "AngularJS": 2,
    "ASP.NET": 3,
    "ASP.NET CORE": 4,
    "Astro": 5,
    "Blazor": 6,
    "CodeIgniter": 7,
    "Deno": 8,
    "Django": 9,
    "Drupal": 10,
    "Elm": 11,
    "Express": 12,
    "FastAPI": 13,
    "Fastify": 14,
    "Flask": 15,
    "Gatsby": 16,
    "Htmx": 17,
    "jQuery": 18,
    "Laravel": 19,
    "NestJS": 20,
    "Next.js": 21,
    "Node.js": 22,
    "Nuxt.js": 23,
    "Phoenix": 24,
    "Play Framework": 25,
    "React": 26,
    "Remix": 27,
    "Ruby on Rails": 28,
    "Solid.js": 29,
    "Spring Boot": 30,
    "Strapi": 31,
    "Svelte": 32,
    "Symfony": 33,
    "Vue.js": 34,
    "WordPress": 35,
    "Yii 2": 36,
    "Other (please specify)": 0
}
mapping_platforms = {
    "Alibaba Cloud": 1,
    "Amazon Web Services (AWS)": 2,
    "Cloudflare": 3,
    "Colocation": 4,
    "Databricks": 5,
    "Digital Ocean": 6,
    "Firebase": 7,
    "Fly.io": 8,
    "Google Cloud": 9,
    "Heroku": 10,
    "Hetzner": 11,
    "IBM Cloud Or Watson": 12,
    "Linode": 13,
    "Managed Hosting": 14,
    "Microsoft Azure": 15,
    "Netlify": 16,
    "OpenShift": 17,
    "OpenStack": 18,
    "Oracle Cloud Infrastructure (OCI)": 19,
    "OVH": 20,
    "PythonAnywhere": 21,
    "Render": 22,
    "Scaleway": 23,
    "Supabase": 24,
    "Vercel": 25,
    "VMware": 26,
    "Vultr": 27,
    "Other (please specify)": 0
}
mapping_database = {
    "BigQuery": 1,
    "Cassandra": 2,
    "Clickhouse": 3,
    "Cloud Firestore": 4,
    "CockroachDB": 5,
    "Cosmos DB": 6,
    "Couch DB": 7,
    "Couchbase": 8,
    "Databricks SQL": 9,
    "Datomic": 10,
    "DuckDB": 11,
    "DynamoDB": 12,
    "Elasticsearch": 13,
    "EventStoreDB": 14,
    "Firebase Realtime Database": 15,
    "Firebird": 16,
    "H2": 17,
    "IBM DB2": 18,
    "InfluxDB": 19,
    "MariaDB": 20,
    "Microsoft Access": 21,
    "Microsoft SQL Server": 22,
    "MongoDB": 23,
    "MySQL": 24,
    "Neo4J": 25,
    "Oracle": 26,
    "PostgreSQL": 27,
    "Presto": 28,
    "RavenDB": 29,
    "Redis": 30,
    "Snowflake": 31,
    "Solr": 32,
    "SQLite": 33,
    "Supabase": 34,
    "TiDB": 35,
    "Other (please specify)": 0
}
mapping_Languages = {
    "Ada": 1,
    "Apex": 2,
    "Assembly": 3,
    "Bash/Shell (all shells)": 4,
    "C": 5,
    "C#": 6,
    "C++": 7,
    "Clojure": 8,
    "Cobol": 9,
    "Crystal": 10,
    "Dart": 11,
    "Delphi": 12,
    "Elixir": 13,
    "Erlang": 14,
    "F#": 15,
    "Fortran": 16,
    "GDScript": 17,
    "Go": 18,
    "Groovy": 19,
    "Haskell": 20,
    "HTML/CSS": 21,
    "Java": 22,
    "JavaScript": 23,
    "Julia": 24,
    "Kotlin": 25,
    "Lisp": 26,
    "Lua": 27,
    "MATLAB": 28,
    "MicroPython": 29,
    "Nim": 30,
    "Objective-C": 31,
    "OCaml": 32,
    "Perl": 33,
    "PHP": 34,
    "PowerShell": 35,
    "Prolog": 36,
    "Python": 37,
    "R": 38,
    "Ruby": 39,
    "Rust": 40,
    "Scala": 41,
    "Solidity": 42,
    "SQL": 43,
    "Swift": 44,
    "TypeScript": 45,
    "VBA": 46,
    "Visual Basic (.Net)": 47,
    "Zephyr": 48,
    "Zig": 49,
    "Other (please specify)": 0
}
mapping_OrgSize = {
    "Just me - I am a freelancer, sole proprietor, etc.": 1,
    "2 to 9 employees": 2,
    "10 to 19 employees": 3,
    "20 to 99 employees": 4,
    "100 to 499 employees": 5,
    "500 to 999 employees": 6,
    "1,000 to 4,999 employees": 7,
    "5,000 to 9,999 employees": 8,
    "10,000 or more employees": 9,
    "I don’t know": 0
}
mapping_DevType = {
    "Academic researcher": 1,
    "Blockchain": 2,
    "Cloud infrastructure engineer": 3,
    "Data or business analyst": 4,
    "Data engineer": 5,
    "Data scientist or machine learning specialist": 6,
    "Database administrator": 7,
    "Designer": 8,
    "Developer Advocate": 9,
    "Developer, AI": 10,
    "Developer, back-end": 11,
    "Developer, desktop or enterprise applications": 12,
    "Developer, embedded applications or devices": 13,
    "Developer Experience": 14,
    "Developer, front-end": 15,
    "Developer, full-stack": 16,
    "Developer, game or graphics": 17,
    "Developer, mobile": 18,
    "Developer, QA or test": 19,
    "DevOps specialist": 20,
    "Educator": 21,
    "Engineer, site reliability": 22,
    "Engineering manager": 23,
    "Hardware Engineer": 24,
    "Marketing or sales professional": 25,
    "Product manager": 26,
    "Project manager": 27,
    "Research & Development role": 28,
    "Scientist": 29,
    "Senior Executive (C-Suite, VP, etc.)": 30,
    "Student": 31,
    "System administrator": 32,
    "Security professional": 33,
    "Qualtrics Survey Software": 34,
    "Other (please specify)":0
}
mapping_EdLevel = {"Primary/elementary school":1,
"Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)":2,
"Some college/university study without earning a degree":3,
"Associate degree (A.A., A.S., etc.)":4,
"Bachelor’s degree (B.A., B.S., B.Eng., etc.)":5,
"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)":6,
"Professional degree (JD, MD, Ph.D, Ed.D, etc.)":7,
"Something else":0}

mapping_codingActivities = {"Hobby":1,
"Freelance/contract work":2,
"Contribute to open-source projects":3,
"Bootstrapping a business":4,
"School or academic work":5,
"Professional development or self-paced learning from online courses":6,
"I don’t code outside of work":7,
"Other (please specify)":0}

mapping_age = {"Under 18 years old":1,
"18-24 years old":2,
"25-34 years old":3,
"35-44 years old":4,
"45-54 years old":5,
"55-64 years old":6,
"65 years or older":7,
"Prefer not to say":0}

mapping_remotework = {"Remote":1,
"In-person":2,
"Hybrid (some remote, some in-person)":3}

mapping_mainbranch = {"I am a developer by profession":1,
"I am not primarily a developer, but I write code sometimes as part of my work/studies":2,
"I used to be a developer by profession, but no longer am":3,
"I am learning to code":4,
"I code primarily as a hobby":5,
"None of these":0}

MAPPING_EMPLOYEMENT = {
"Employed, full-time":1,
"Employed, part-time":2,
"Independent contractor, freelancer, or self-employed":3,
"Not employed, but looking for work":4,
"Not employed, and not looking for work":5,
"Student, full-time":6,
"Student, part-time":7,
"Retired":8,
"I prefer not to say":1}
